### ISSUE TITLE
Add backup of database

### ISSUE THREAD

**Issue by errotu** [KallanX/mattermost-upgrade-script#11]
I just noticed that the script currently does not backup the database. The Mattermost documentation [explicitly recommends it](https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html):

> 6. Back up your data and application. Make sure you’ve properly backed up your database before continuing with the upgrade. In case of an unexpected failure, you should be in a position to load a previous database snapshot.
>
>     a. Back up your database using your organization’s standard procedures for backing up MySQL or PostgreSQL.

This could probably be achieved by a simple mysqldump-command, backing the database up into a file.

Would you be interested in adding this feature?

**Comment by KallanX** [comment]
This has been added to main. I was unable to test the MySQL backup as I use Mattermost on PostgreSQL. If you could test it and let me know if there are any issues, that would be great.

**Comment by errotu** [comment]
Thanks a lot! Unfortunately, it currently does not work (for me). I provided some bugfixes but was unable to fetch the password via grep. Do you know if it's regularly necessary for mysqldump? At least my hoster let's me execute mysqldump without providing a password (as a .my.cnf-file exists).
