### ISSUE TITLE
License

### ISSUE THREAD

**Issue by errotu** [KallanX/mattermost-upgrade-script#3]
Thanks a lot for your script! I am going to use it in a slightly modified version, as my hosting service does not allow any root permissions. Could you formally [license your project](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) (e.g. with the MIT license, but [see also this overview](https://choosealicense.com/))?

I'd then be able to publish a fork without worrying to much if a simple (albeit very helpful!) script is falling under copyright protection.

**Comment by KallanX** [comment]
Hey! You're very welcome and thank you for your interest in the script. I have added the MIT license to the source code.

Enjoy!

**Comment by errotu** [comment]
Perfect, thanks a lot!
