### ISSUE TITLE
Possible Improvement - Auto-Updater

### ISSUE THREAD

**Issue by errotu** [KallanX/mattermost-upgrade-script#7]
First of all: Thanks for your work and your input!

Did you ever think about automatizing the upgrade script?

The current version installed [could be retrieved via](https://docs.mattermost.com/manage/mmctl-command-line-tool.html#mmctl-version)
> ./bin/mmctl version

and then checked against the current version available on the Github releases feed
> https://github.com/mattermost/platform/releases.atom

It would possibly make sense to have two versions of the script, one only for minor and one for major upgrades.

Like this, one could use the script for a daily cronjob and it would be ensured that the installation is up-to-date without any need to check manually for updates.

**Comment by KallanX** [comment]
Hey. Yeah, no problem. Happy to help.

Check the latest changes in main. I added an initial cron (automated) script. I also updated the base Mattermost upgrade script with a new prompts function. Trying to clean it up a bit.

You'll find notes for the new cron script in the README.

Cheers

**Comment by errotu** [comment]
Great, thanks a lot!
